apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
      - name: java-backend
        image: wbrymo/java-ecomm-backend:latest
        ports:
        - containerPort: 8080
