apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: java-ecomm-cluster
  region: us-east-1

vpc:
  id: "vpc-030180ef7b3372ec4"
  subnets:
    public:
      us-east-1a:
        id: "subnet-018a0920ef1cc9d97"
      us-east-1b:
        id: "subnet-09bdf95b8d7f564c3"

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
